import os
import json
from pathlib import Path
from typing import List, Tuple
from langchain_groq import ChatGroq
from pydantic import BaseModel
from langchain_core.output_parsers import PydanticOutputParser
from langchain_core.prompts import PromptTemplate
from typing import Optional


GROQ_API_KEY = os.getenv("GROQ_API_KEY")
DOCGEN_FILE_LIMIT = 200


# Default Groq models
SUMMARIZER_MODEL = os.getenv("MODEL_SUMMARIZER")
DOCGEN_MODEL = os.getenv("MODEL_DOCGEN")

def _collect_folder_files(folder: Path) -> List[Tuple[str, bytes]]:
    files: List[Tuple[str, bytes]] = []
    for path in folder.rglob("*"):
        if path.is_file():
            try:
                files.append((str(path.relative_to(folder)), path.read_bytes()))
            except OSError:
                # Skip unreadable files but continue processing
                continue
    return files

def _build_project_tree_from_paths(
    rel_paths: list[str],
    max_entries: int = 200,
) -> str:
    """
    Build a simple tree view from a list of relative paths like:
      ["src/main.jsx", "src/components/Button.jsx", "README.md"]
    """
    if not rel_paths:
        return "(project appears empty)"

    entries: list[str] = []
    count = 0

    for rel in sorted(rel_paths):
        if count >= max_entries:
            entries.append("  ...")
            break

        parts = [p for p in rel.split("/") if p]  # remove empty segments
        if not parts:
            continue

        indent = "  " * (len(parts) - 1)
        name = parts[-1]
        # crude heuristic: treat anything with a dot as a file
        marker = "📄" if "." in name else "📁"
        entries.append(f"{indent}{marker} {name}")
        count += 1

    return "\n".join(entries)


def _fallback_generate_docs_from_paths(
    files: list[tuple[str, bytes]],
    project_id: str | None = None,
) -> dict:
    """
    Fallback doc generator that works purely from an in-memory list of
    (relative_path_inside_project, file_bytes).

    This is the in-memory equivalent of `_fallback_generate_docs(...)`.
    """
    # We only care about the relative paths here
    rel_paths = [rel for (rel, _data) in files[:DOCGEN_FILE_LIMIT]]

    file_list = "\n".join(f"- {rel}" for rel in rel_paths) or "No readable files were detected."
    project_tree = _build_project_tree_from_paths(rel_paths)

    project_label = project_id or "this project"

    readme = f"""# Project Overview

This README was generated using the fallback documentation routine because the primary doc generation LLM was unavailable.

## Project

- Project ID: `{project_label}`

## Project Structure

{project_tree}

## Files Analysed

{file_list}

## Next Steps

- Replace this placeholder README with project-specific documentation.
- Review `USER_MANUAL.md` for basic usage instructions generated by the fallback routine.
"""

    user_manual = f"""# User Manual (Fallback)

This document was produced by the fallback documentation routine. Please update it with project-specific instructions.

## Getting Started

1. Review the project structure shown in the README.
2. Install any required dependencies.
3. Run the project following your usual workflow (e.g. `npm install`, `npm run dev`, etc.).

## Usage

- This manual was generated without deep semantic analysis of the code.
- You should add:
  - Screenshots or key UI flows.
  - Setup steps for environment variables, API keys, etc.
  - Any domain-specific instructions your users need.

## Support

Since this documentation was generated without analyzing the code semantically,
manual verification and refinement are strongly recommended.
"""

    return {
        "readme": readme,
        "user_manual": user_manual,
    }


def get_groq_llm(model: str = DOCGEN_MODEL):
    """Return a ChatGroq LLM if available and configured, else raise a helpful error."""
    if ChatGroq is None:
        raise ImportError(
            "langchain_groq is not installed. Install with `pip install langchain-groq`."
        )
    if not GROQ_API_KEY :
        raise EnvironmentError("GROQ_API_KEY is not set. Please set it in your environment.")
    return ChatGroq(model=model, api_key=GROQ_API_KEY , temperature=0)


def get_model_for(task: str):
    """Quick model switcher for 'summarizer' / 'docgen'."""
    if task == "summarizer":
        return get_groq_llm(model=SUMMARIZER_MODEL)
    if task == "docgen":
        return get_groq_llm(model=DOCGEN_MODEL)
    raise ValueError(f"Unknown task: {task}")

class FunctionSummary(BaseModel):
    name: str
    description: str
    parameters: List[str] = []
    returns: str = ""


class FileSummary(BaseModel):
    file_name: str
    imports: List[str] = []
    functions: List[FunctionSummary] = []
    purpose: str = ""


class DocOutputs(BaseModel):
    readme: str
    user_manual: str

    # Summarizer utilities

# Parser for summarizer output
summarizer_parser = PydanticOutputParser(pydantic_object=FileSummary)

# Prompt template with stronger instructions
SUMMARIZER_PROMPT = """
You are a precise code summarizer. Analyze the following code (single file chunk) and return a JSON matching the schema.

File name: {file_name}

Code chunk:
{code}

INSTRUCTIONS:
- Always include **all fields** of the schema (imports, functions, purpose, etc.).
- If something is missing, fill with an empty string "" or an empty list [].
- For 'functions': include name, description, parameters (list of strings), and returns.
- For 'purpose': if no clear purpose, set it to "".
- Respond ONLY with valid JSON that matches the schema.

{format_instructions}
"""

def chunk_text(text: str, max_chars: int = 3000):
    """Naive character-based chunking"""
    return [text[i:i + max_chars] for i in range(0, len(text), max_chars)]

def summarize_file(file_name: str, code: str, llm=None) -> FileSummary:
    if llm is None:
        llm = get_model_for("summarizer")

    prompt = PromptTemplate(
        template=SUMMARIZER_PROMPT,
        input_variables=["file_name", "code"],
        partial_variables={"format_instructions": summarizer_parser.get_format_instructions()},
    )

    # modern chain → prompt | llm | parser
    chain = (prompt | llm | summarizer_parser)

    chunks = chunk_text(code, max_chars=3000)
    merged = {"file_name": file_name, "imports": [], "functions": [], "purpose": ""}

    for i, ch in enumerate(chunks):
        try:
            file_summary: FileSummary = chain.invoke({"file_name": file_name, "code": ch})
        except Exception:
            # fallback: skip invalid chunk
            continue

        # Merge imports
        for imp in file_summary.imports:
            if imp not in merged["imports"]:
                merged["imports"].append(imp)

        # Merge functions (avoid duplicates)
        for fn in file_summary.functions:
            if fn.name not in [f["name"] for f in merged["functions"]]:
                merged["functions"].append(fn.dict())

        # Merge purpose (keep first non-empty)
        if not merged["purpose"] and file_summary.purpose:
            merged["purpose"] = file_summary.purpose

    # Defensive autofill
    final = FileSummary(**merged)
    if final.purpose is None:
        final.purpose = ""
    for fn in final.functions:
        if fn.returns is None:
            fn.returns = ""

    return final

def summarize_many(files: List[tuple], llm=None) -> List[FileSummary]:
    """Summarize many files: files is list of (filename, bytes)."""
    results = []
    if llm is None:
        llm = get_model_for("summarizer")

    for fname, content in files:
        try:
            code_text = content.decode("utf-8", errors="ignore")
        except Exception:
            code_text = str(content)
        summary = summarize_file(fname, code_text, llm=llm)
        results.append(summary)
    return results


# Doc generation utilities

doc_parser = PydanticOutputParser(pydantic_object=DocOutputs)

DOC_PROMPT = """
You are a professional technical writer responsible for generating both README and User Manual files.

PROJECT_SUMMARIES (JSON):
{summaries_json}

REFERENCE TEMPLATES:
If both templates are provided, they will appear below:

<README_TEMPLATE>
{readme_template}
</README_TEMPLATE>

<USER_MANUAL_TEMPLATE>
{manual_template}
</USER_MANUAL_TEMPLATE>

INSTRUCTIONS:
- Generate TWO separate markdown documents:
  1. "readme" → Follow the README_TEMPLATE structure and tone.
  2. "user_manual" → Follow the USER_MANUAL_TEMPLATE structure and tone.
- If any template is missing, generate that file using a clear, informative default format.
- Always return output as a **valid JSON** with keys:
  - "readme"
  - "user_manual"
- Use PROJECT_SUMMARIES to fill in meaningful details (functions, modules, dependencies, usage, etc.)
- Avoid copying the templates verbatim; treat them as layout guides.
- Ensure proper markdown formatting.
{format_instructions}
"""


def generate_docs(summaries: List[dict], readme_template: str = "", manual_template: str = "", llm=None) -> dict:
    if llm is None:
        llm = get_model_for("docgen")

    summaries_json = json.dumps([s.dict() if hasattr(s, "dict") else s for s in summaries], indent=2)

    prompt = PromptTemplate(
        template=DOC_PROMPT,
        input_variables=["readme_template", "manual_template", "summaries_json"],
        partial_variables={"format_instructions": doc_parser.get_format_instructions()}
    )

    # LCEL pipeline: prompt | llm | parser
    chain = (prompt | llm | doc_parser)
    outputs: DocOutputs = chain.invoke({
        "readme_template": readme_template,
        "manual_template": manual_template,
        "summaries_json": summaries_json
    })

    return {"readme": outputs.readme, "user_manual": outputs.user_manual}

def genie_docgen(
    folder_path: Path | str,
    files: Optional[List[Tuple[str, bytes]]] | None = None,
) -> dict:
    'Generate README and User Manual content from an uploaded project directory.'
    folder = Path(folder_path)

    readme_template_path = Path(r"C:\Users\megha\Documents\Doc_generation\README (3).md")
    manual_template_path = Path(r"C:\Users\megha\Documents\Doc_generation\um-1.md")

    def _safe_read_text(template_path: Path) -> str:
        try:
            return template_path.read_text(encoding="utf-8")
        except OSError:
            return ""

    readme_template = _safe_read_text(readme_template_path)
    manual_template = _safe_read_text(manual_template_path)

    if files is None:
        files = _collect_folder_files(folder)

    if not files:
        raise ValueError('Uploaded project is empty or unreadable.')

    limited_files = files[:DOCGEN_FILE_LIMIT]
    summarizer_llm = get_model_for('summarizer')
    summaries = summarize_many(limited_files, llm=summarizer_llm)

    docgen_llm = get_model_for('docgen')
    docs = generate_docs(
        summaries=summaries,
        readme_template=readme_template,
        manual_template=manual_template,
        llm=docgen_llm,
    )

    return {
        'readme': docs.get('readme', ''),
        'user_manual': docs.get('user_manual', ''),
    }
